### ISSUE TITLE
Better how to guide and explanation

### ISSUE THREAD

**Issue by bart88** [universityofadelaide/docker-drupal8#1]
The readme makes a lot of assumptions about the user. 
- That they understand what robo is and why it is used.
- Know the benefits of using docker against vagrant.
- Know how how to traverse all the docker commands to troubleshoot.

I think the readme should be more detailed and provide explanations of the process in order to make it more accessible to the Drupal community.

**Comment by pingers** [comment]
Yeah... I have no idea what all of our readme's are about in the docker repo's. They need to be a lot more descriptive. Let's raise the bar a bit... especially on public repo's.
Let's try and figure out a standard format we can agree on.

**Comment by singularo** [comment]
Also ancient, closing.
