### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by bart88** [universityofadelaide/docker-drupal8#11]
As above, this should be a requirement for all public repos added. Any ideas on what license ?

**Comment by pingers** [comment]
MIT or GPL... I don't mind too much, but lean towards MIT.

**Comment by pingers** [comment]
http://choosealicense.com/

**Comment by bart88** [comment]
I agree with MIT. @singularo any opinion on this ?

**Comment by TigerWolf** [comment]
✔️  MIT
