### ISSUE TITLE
Setup docker-machine not called in start.sh

### ISSUE THREAD

**Issue by bart88** [universityofadelaide/docker-drupal8#7]
There is a method in `common.sh` that setups docker machine ( for Mac OS X and Windows ) users this isn't called in `./start.sh` 

Is it assumed that the user will have a docker machine running as 'default' ?

**Comment by TigerWolf** [comment]
Pretty sure docker installation creates that one.

**Comment by bart88** [comment]
This is for docker toolbox users. Yes it will be different with docker for mac / windows.

**Comment by bart88** [comment]
Fixed
